#cloud-config

#users:
#- name: cloudservice
#  groups: user
#  uid: 2000

write_files:

- path: /etc/entrypoint.sh
  owner: root
  permissions: 0744
  owner: root
  content: |
    set -e
    mkdir /etc/lcp
    git clone https://github.com/readium/readium-lcp-server.git /etc/lcp
    cd /etc/lcp
    git checkout cd
    echo "$PWD"
    ls -la

    /usr/bin/docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD -w=$PWD docker/compose:1.29.2 -f $PWD/docker/docker-compose.yml up

- path: /etc/entrypoint_stop.sh
  owner: root
  permissions: 0744
  owner: root
  content: |

    /usr/bin/docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD -w=$PWD docker/compose:1.29.2 -f $PWD/docker/docker-compose.yml stop


- path: /etc/systemd/system/readiumlcp.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start the readium lcp server

    [Service]
    ExecStart=/bin/sh /etc/entrypoint.sh
    ExecStop=/bin/sh /etc/entrypoint_stop.sh
    #ExecStopPost=/usr/bin/docker rm mycloudservice

runcmd:
- systemctl daemon-reload
- systemctl start readiumlcp.service

# Optional once-per-boot setup. For example: mounting a PD.
#bootcmd:
  #- fsck.ext4 -tvy /dev/[DEVICE_ID]
  #- mkdir -p /mnt/disks/[MNT_DIR]
  #- mount -t ext4 -O ... /dev/[DEVICE_ID] /mnt/disks/[MNT_DIR]
