steps:
  # Docker Build
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/libuserkey.a', '/workspace/libuserkey.a']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/userkey.h', '/workspace/userkey.h']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/user_key.go', '/workspace/user_key.go']
  - name: ubuntu
    entrypoint: bash
    args:
      - -c
      - |
        ls -la /workspace

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
    'europe-west1-docker.pkg.dev/lcpserver-1/lcp-server-build/readium-lcp-server-build-prod:latest', 
    '-f', 'docker/Dockerfile',
    '--build-arg', 'LIBUSERKEY_PATH=/libuserkey.a',
    '--build-arg', 'USERKEYH_PATH=/userkey.h',
    '--build-arg', 'USERKEYGO_PATH=/user_key.go',
    '--build-arg', 'BUILD_PROD=true',
    '.']
    timeout: 3600s

    # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
    'europe-west1-docker.pkg.dev/lcpserver-1/lcp-server-build/readium-lcp-server-build-prod:latest']

