# Configuration for lcpserver and lsdserver

# Shared configuration

# The usernames and passwords must match the ones in the htpasswd files for each server.

lcp:
    public_base_url:  "${LCP_BASE_URL}"
lcp_update_auth: 
    username: "${LCP_UPDATE_AUTH_USER}"
    password: "${LCP_UPDATE_AUTH_PASS}"

lsd:
    public_base_url:  "${LSD_BASE_URL}"
lsd_notify_auth: 
    username: "${LSD_NOTIFY_AUTH_USER}"
    password: "${LSD_NOTIFY_AUTH_PASS}"


# LCP Server

profile: "${PROFILE}"
lcp:
    host: "${LCP_HOST}"
    port: ${LCP_PORT}
    database: "${LCP_DATABASE}"
    auth_file: "${AUTH_FILE}"
storage:
    filesystem:
        directory: "${LCP_STORAGE_PATH}"
certificate:
    cert: "${CERTIFICATE_PATH}"
    private_key: "${PRIVATE_KEY}"
license:
    links:
        status: "${PUBLIC_URL}/licenses/{license_id}/status"
        hint: "${PUBLIC_URL}/static/hint.html"
        publication: "${PUBLIC_URL}/contents/{publication_id}"


# LSD Server

lsd:
    host: "${LSD_HOST}"
    port: ${LSD_PORT}
    database: "${LSD_DATABASE}"
    auth_file: "${AUTH_FILE}"
    license_link_url: "${PUBLIC_URL}/api/v1/licenses/{license_id}"
license_status:
    register: true
    renew: true
    return: true
    renting_days: 60
    renew_days: 7
